server:
  port: 8000

spring:
  application:
    name: service-user
  datasource:
    url: jdbc:mysql://localhost:3307/mystore?serverTimezone=UTC&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: properties
        import-check:
          enabled: false
    openfeign:
      client:
        config:
          default:
            logger-level: full
            connect-timeout: 300
            read-timeout: 2000
#service-store以及其他可单独配置
    sentinel:
      transport:
        dashboard: localhost:8081
      eager: true
      web-context-unify: false
  rabbitmq:
    password: guest
    username: guest
    host: localhost
    port: 5672
    listener:
      simple:
        acknowledge-mode: auto

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.cloud.user.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

seata:
  enabled: true
  application-id: ${spring.application.name:}
  # 直接配置 Seata Server 地址（file模式）
  service:
    vgroup-mapping:
      order-service-group: default
    grouplist:
      default: 127.0.0.1:8091  # Seata Server 地址
#    disable-global-transaction: true
  # 配置中心和注册中心都用 file 模式
  config:
    type: file

  registry:
    type: file

  # 数据源代理配置
  data-source-proxy-mode: AT
  tx-service-group: order-service-group


jwt:
  secret: 6Nq7Xp9kL2mR4vB8wC1eF5hJ3yU7iA0cD9gH4jK6nM2